version: "3.9"

services:

  postgres:
    image: postgres:alpine
    container_name: mira-postgres
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    network_mode: bridge
    env_file: ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
